import styles from "../../../styles/Info.module.css";

export default function Redovisning2023() {
  return (
    <div className={styles.details}>
      <h1>Approved Annual Report – December 31, 2023 </h1>
      <h4>22024-08-30</h4>
      <p></p>
      <div className={styles.articlesimage}>
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_01.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_02.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_03.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_04.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_05.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_06.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_07.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_08.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_09.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_10.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_11.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_12.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_13.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_14.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_15.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_16.jpg"
          alt="Årsredovisning2023"
        />
        <img
          className={styles.image1}
          src="/Nyheter/2023_Sida_17.jpg"
          alt="Årsredovisning2023"
        />
      </div>
    </div>
  );
}
